spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      instanceProfile: true
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    cloudfront: ${CDN_PATH}

server:
  domain:
    local: ${NAMO_LOCAL_DOMAIN:127.0.0.1:8080}
    service: ${NAMO_SERVICE_DOMAIN:127.0.0.1:8080}

app:
  image:
    url:
      meeting: ${BASE_MOIM_IMAGE_URL}

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod
