spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:namo-v2}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnect=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    data-source-properties:
      rewrite-batched-statements: true

---
spring.config.activate.on-profile: local

spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/dev
  jpa:
    database: MySQL
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    ROOT: INFO
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.sql: debug
    org.hibernate.type: trace
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.springframework.orm: TRACE
    org.springframework.transaction: TRACE
    com.zaxxer.hikari: TRACE
    com.mysql.cj.jdbc: TRACE

---
spring.config.activate.on-profile: dev

spring:
  jpa:
    database: MySQL
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/dev

---
spring.config.activate.on-profile: prod

spring:
  jpa:
    database: MySQL
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---
spring.config.activate.on-profile: test

spring:
  jpa:
    database: MySQL
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false

logging:
  level:
    org.springframework.jdbc: debug
