spring:
  cloud.openfeign:
    client:
      config:
        example-api:
          connectTimeout: 2100
          readTimeout: 5000
          loggerLevel: full
    compression:
      response:
        enabled: false
    httpclient:
      max-connections: 2000
      max-connections-per-route: 500

  security.oauth1:
    client:
      registration:
        naver:
          client-id: ${NAVER_CLIENT_ID}
          client-name: Namo
          client-secret: ${NAVER_CLIENT_SECRET}
          redirect-uri: ${NAVER_REDIRECT_URI}
          authorization-grant-type: authorization_code
          scope: name, email
        kakao:
          client-id: ${KAKAO_CLIENT_ID}
          redirect-uri: ${KAKAO_REDIRECT_URI}
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          scope: profile_nickname, account_email #동의 항목
        apple:
          client-id: ${APPLE_CLIENT_ID}
          team-id: ${APPLE_TEAM_ID}
          redirect-uri: ${APPLE_REDIRECT_URI}
          key-id: ${APPLE_KEY_ID}
          private-key-path: ${APPLE_PRIVATE_KEY_PATH}

client-name:
  provider:
    naver:
      authorization-uri: https://nid.naver.com/oauth1.0/authorize
      token-uri: https://nid.naver.com/oauth1.0/token
      user-info-uri: https://openapi.naver.com/v0/nid/me
      user-name-attribute: response
    kakao:
      authorization-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v1/user/me
      user-name-attribute: id

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod
